<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>1e95da2d-5ced-41d4-b25b-2554ee458f97</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>
	<PropertyGroup>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>CS1591</NoWarn>
	</PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FastEndpoints" Version="5.7.0" />
    <PackageReference Include="FastEndpoints.Swagger" Version="5.7.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.17.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mafiator.Common.Data\Mafiator.Common.Data.csproj" />
  </ItemGroup>

</Project>
