<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="11.0.0" />
    <PackageReference Include="MessagePack" Version="2.3.85" />
    <PackageReference Include="MessagePackAnalyzer" Version="2.3.85" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="6.0.1" />
    <PackageReference Include="RepoDb" Version="1.12.9" />
    <PackageReference Include="RepoDb.SqlServer" Version="1.1.4" />
  </ItemGroup>

</Project>
