<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="KavenegarDotNetCore" Version="1.0.3" />
    <PackageReference Include="MailKit" Version="3.1.0" />
    <PackageReference Include="Microsoft.Azure.Management.Media" Version="5.0.0" />
    <PackageReference Include="Microsoft.Azure.NotificationHubs" Version="4.1.0" />
    <PackageReference Include="Microsoft.Azure.SignalR" Version="1.15.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="4.1.1-dev-00229" />
    <PackageReference Include="Serilog.Extensions.Logging.File" Version="2.0.0" />
    <PackageReference Include="SmsIrRestfulNetCore" Version="1.1.4" />
    <PackageReference Include="Twilio" Version="5.70.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mafiator.Common.Server\Mafiator.Common.Server.csproj" />
    <ProjectReference Include="..\Mafiator.Repository\Mafiator.Repository.csproj" />
  </ItemGroup>

</Project>
