global using FastEndpoints;
global using Mafiator.Api.Constants;
global using Mafiator.API.Constants;
global using Mafiator.Common.Data.Dtos.Api;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using System.Threading;
global using System.Threading.Tasks;