<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <UserSecretsId>cd45931b-b57d-4098-bcb4-aef3f70acfa2</UserSecretsId>
    <DockerDefaultTargetOS>Windows</DockerDefaultTargetOS>
    <GenerateRuntimeConfigurationFiles>True</GenerateRuntimeConfigurationFiles>
    <ApplicationInsightsResourceId>/subscriptions/23cb6aaa-477e-4b65-b757-7e45ff2549e5/resourceGroups/main/providers/microsoft.insights/components/MafiatorApi</ApplicationInsightsResourceId>

  </PropertyGroup>

  <ItemGroup>
    
    <PackageReference Include="Ardalis.ApiEndpoints" Version="4.0.1" />
    
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.21.0" />
    
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
 
  <ItemGroup>
    <ProjectReference Include="..\Mafiator.IocConfig\Mafiator.IocConfig.csproj" />
  </ItemGroup>


</Project>
