<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire" Version="1.7.28" />
    <PackageReference Include="MessagePack.AspNetCoreMvcFormatter" Version="2.3.85" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Facebook" Version="6.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="6.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.MessagePack" Version="6.0.1" />
    <PackageReference Include="NSwag.AspNetCore" Version="13.15.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mafiator.Service\Mafiator.Service.csproj" />
  </ItemGroup>

</Project>
