<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net7.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MemoryPack.AspNetCoreMvcFormatter" Version="1.9.7" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.Facebook" Version="7.0.1" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="7.0.1" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="7.0.1" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="5.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.MessagePack" Version="7.0.1" />
		<PackageReference Include="Scrutor" Version="4.2.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
		<PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="6.4.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Mafiator.Service\Mafiator.Service.csproj" />
	</ItemGroup>

</Project>
