//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mafiator.Game.Resources.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mafiator.Game.Resources.Texts.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Friends.
        /// </summary>
        internal static string AddFriends {
            get {
                return ResourceManager.GetString("AddFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your friends in this room so you can be in touch and play together.
        /// </summary>
        internal static string AddFriendsDesc {
            get {
                return ResourceManager.GetString("AddFriendsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow notifications.
        /// </summary>
        internal static string AllowNotifications {
            get {
                return ResourceManager.GetString("AllowNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everybody has a power.
        /// </summary>
        internal static string AppSubTitle {
            get {
                return ResourceManager.GetString("AppSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mafiator.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a room.
        /// </summary>
        internal static string ARoom {
            get {
                return ResourceManager.GetString("ARoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoplay voices in game.
        /// </summary>
        internal static string Autoplay {
            get {
                return ResourceManager.GetString("Autoplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        internal static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        internal static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        internal static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code cannot be empty.
        /// </summary>
        internal static string EmptyCode {
            get {
                return ResourceManager.GetString("EmptyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password cannot be empty.
        /// </summary>
        internal static string EmptyConfirmPassword {
            get {
                return ResourceManager.GetString("EmptyConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input cannot be empty.
        /// </summary>
        internal static string EmptyInput {
            get {
                return ResourceManager.GetString("EmptyInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be empty.
        /// </summary>
        internal static string EmptyPassword {
            get {
                return ResourceManager.GetString("EmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number cannot be empty.
        /// </summary>
        internal static string EmptyPhoneNo {
            get {
                return ResourceManager.GetString("EmptyPhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username cannot be empty.
        /// </summary>
        internal static string EmptyUsername {
            get {
                return ResourceManager.GetString("EmptyUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter verification code sent to.
        /// </summary>
        internal static string EnterCode {
            get {
                return ResourceManager.GetString("EnterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Room Name.
        /// </summary>
        internal static string EnterRoomName {
            get {
                return ResourceManager.GetString("EnterRoomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Played.
        /// </summary>
        internal static string GamePlayed {
            get {
                return ResourceManager.GetString("GamePlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to game.
        /// </summary>
        internal static string GoToGame {
            get {
                return ResourceManager.GetString("GoToGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least 6 characters inclusing letters and digits.
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        internal static string Join {
            get {
                return ResourceManager.GetString("Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string LanguageColon {
            get {
                return ResourceManager.GetString("LanguageColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave.
        /// </summary>
        internal static string Leave {
            get {
                return ResourceManager.GetString("Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging in....
        /// </summary>
        internal static string LoggingIn {
            get {
                return ResourceManager.GetString("LoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Count.
        /// </summary>
        internal static string MemberCount {
            get {
                return ResourceManager.GetString("MemberCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members(s).
        /// </summary>
        internal static string Memberss {
            get {
                return ResourceManager.GetString("Memberss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a new game.
        /// </summary>
        internal static string NewGame {
            get {
                return ResourceManager.GetString("NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Room.
        /// </summary>
        internal static string NewRoom {
            get {
                return ResourceManager.GetString("NewRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new game is scheduled to start!.
        /// </summary>
        internal static string NoGame {
            get {
                return ResourceManager.GetString("NoGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Room.
        /// </summary>
        internal static string NoRoom {
            get {
                return ResourceManager.GetString("NoRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play music.
        /// </summary>
        internal static string PlayMusic {
            get {
                return ResourceManager.GetString("PlayMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Sound.
        /// </summary>
        internal static string PlaySound {
            get {
                return ResourceManager.GetString("PlaySound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Room.
        /// </summary>
        internal static string PrivateRoom {
            get {
                return ResourceManager.GetString("PrivateRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re registering your account.
        /// </summary>
        internal static string RegisteringAccount {
            get {
                return ResourceManager.GetString("RegisteringAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend Code.
        /// </summary>
        internal static string Resend {
            get {
                return ResourceManager.GetString("Resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles in game:.
        /// </summary>
        internal static string RolesInGame {
            get {
                return ResourceManager.GetString("RolesInGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Code.
        /// </summary>
        internal static string RoomCode {
            get {
                return ResourceManager.GetString("RoomCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan room barcode to join immediately.
        /// </summary>
        internal static string RoomCodeDesc {
            get {
                return ResourceManager.GetString("RoomCodeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms.
        /// </summary>
        internal static string Rooms {
            get {
                return ResourceManager.GetString("Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Barcode.
        /// </summary>
        internal static string ScanBarcode {
            get {
                return ResourceManager.GetString("ScanBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Avatar.
        /// </summary>
        internal static string SelectAvatar {
            get {
                return ResourceManager.GetString("SelectAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OOPS!!Server error occured. Please try again later.
        /// </summary>
        internal static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        internal static string Set {
            get {
                return ResourceManager.GetString("Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Profile Picture....
        /// </summary>
        internal static string SetPP {
            get {
                return ResourceManager.GetString("SetPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        internal static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        internal static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total win.
        /// </summary>
        internal static string TotalWin {
            get {
                return ResourceManager.GetString("TotalWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Profile Picture.
        /// </summary>
        internal static string UploadPP {
            get {
                return ResourceManager.GetString("UploadPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating verification code....
        /// </summary>
        internal static string ValidatingCode {
            get {
                return ResourceManager.GetString("ValidatingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code.
        /// </summary>
        internal static string VerificationCode {
            get {
                return ResourceManager.GetString("VerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win as citizen.
        /// </summary>
        internal static string WinAsCitizen {
            get {
                return ResourceManager.GetString("WinAsCitizen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win as mafia.
        /// </summary>
        internal static string WinAsMafia {
            get {
                return ResourceManager.GetString("WinAsMafia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your country.
        /// </summary>
        internal static string YourCountry {
            get {
                return ResourceManager.GetString("YourCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your language.
        /// </summary>
        internal static string YourLanguage {
            get {
                return ResourceManager.GetString("YourLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms you play in.
        /// </summary>
        internal static string YourRooms {
            get {
                return ResourceManager.GetString("YourRooms", resourceCulture);
            }
        }
    }
}
